const TABLE_HEADERS=['日期/受伤类型','扭伤','擦伤','地点','中暑','磕伤','美甲撕裂','腹泻','头晕','头痛','感冒','脱臼','骨折','地点','过敏','痛经','测血压','其他','合计','接诊医生','备注'];
const TABLE_DISEASE_COLUMNS=['扭伤','擦伤','中暑','磕伤','美甲撕裂','腹泻','头晕','头痛','感冒','脱臼','骨折','过敏','痛经','测血压'];
const DEFAULT_DISEASES=TABLE_DISEASE_COLUMNS.concat(['其他']);
const DEFAULT_PLACES=['极速飞车','水晶神翼','雪域金翅','喜马拉雅雄鹰','家庭过山车','淘气堡','乐迪历险记'];
const PLACE_REQUIRED_DISEASES=['擦伤','骨折'];

const app={
 records:[],tableRows:[],suppressSuggestUntil:0,suggestTouch:null,config:{lastPark:'水园',lastDoctor:'',customDiseases:[],customPlaces:[],customLocations:[]},
 init(){this.setupInputs();this.loadConfig();this.updatePlaceRequired();this.updateRecordList();},
 loadConfig(){const s=localStorage.getItem('medicalConfig');if(!s)return;try{this.config=Object.assign({},this.config,JSON.parse(s));this.config.customDiseases=this.unique(this.config.customDiseases||[]);this.config.customPlaces=this.unique((this.config.customPlaces||[]).concat(this.config.customLocations||[]));document.getElementById('park').value=this.config.lastPark||'水园';document.getElementById('doctor').value=this.config.lastDoctor||'';}catch(e){localStorage.removeItem('medicalConfig');}},
 saveConfig(){localStorage.setItem('medicalConfig',JSON.stringify(this.config));},
 setupInputs(){['disease','doctor','onsetPlace'].forEach(id=>{const el=document.getElementById(id);if(!el)return;el.removeAttribute('readonly');el.removeAttribute('disabled');el.addEventListener('touchend',()=>setTimeout(()=>this.focusInput(el),0),{passive:true});el.addEventListener('click',()=>this.focusInput(el));});this.bindSuggest('disease','diseaseSuggest',()=>this.getDiseaseOptions(),'疾病');this.bindSuggest('onsetPlace','placeSuggest',()=>this.getPlaceOptions(),'地点');document.getElementById('disease').addEventListener('input',()=>this.updatePlaceRequired());document.getElementById('disease').addEventListener('change',()=>this.updatePlaceRequired());document.getElementById('visit').addEventListener('change',()=>this.updatePlaceRequired());document.addEventListener('pointerdown',e=>{if(!e.target.closest('.suggest-wrap'))this.hideSuggests();});document.addEventListener('keydown',e=>{if(e.key==='Escape')this.hideSuggests();});},
 focusInput(el){if(!el)return;if(document.activeElement!==el)el.focus();const n=el.value.length;if(typeof el.setSelectionRange==='function')el.setSelectionRange(n,n);},
 bindSuggest(inputId,listId,getOptions,label){const input=document.getElementById(inputId),box=document.getElementById(listId);if(!input||!box)return;input.parentElement.classList.add('suggest-wrap');input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls',listId);box.setAttribute('role','listbox');box.dataset.activeIndex='-1';const show=()=>this.showSuggest(input,box,getOptions(),label);input.addEventListener('input',show);input.addEventListener('focus',show);input.addEventListener('click',show);input.addEventListener('keydown',e=>this.handleSuggestKey(e,input,box));},
 showSuggest(input,box,options,label){if(Date.now()<this.suppressSuggestUntil)return;const kw=input.value.trim(),uniqueOptions=this.unique(options),matched=uniqueOptions.filter(v=>!kw||v.includes(kw)).slice(0,12),exists=kw&&uniqueOptions.includes(kw);let rows=matched.map(v=>({value:v,tag:this.isCustomOption(label,v)?'自定义':'常用',hint:''}));if(kw&&!exists)rows.unshift({value:kw,tag:'新增',hint:`使用并保存这个${label}`});if(rows.length===0){box.innerHTML='';box.classList.remove('show');input.setAttribute('aria-expanded','false');return;}box.innerHTML=rows.map((r,i)=>`<div class="suggest-item" role="option" id="${box.id}-item-${i}" data-index="${i}" data-value="${this.escapeHtml(r.value)}"><span class="suggest-main">${this.highlightText(r.value,kw)}</span><span class="suggest-meta">${r.hint||r.tag}</span></div>`).join('');box.dataset.activeIndex='-1';box.classList.add('show');input.setAttribute('aria-expanded','true');box.querySelectorAll('.suggest-item').forEach(it=>this.bindSuggestItem(it,input,box));},
 handleSuggestKey(e,input,box){if(!box.classList.contains('show')){if(e.key==='ArrowDown'||e.key==='Enter')this.showInputSuggest(input.id);return;}const items=Array.from(box.querySelectorAll('.suggest-item'));if(items.length===0)return;let idx=Number(box.dataset.activeIndex||-1);if(e.key==='ArrowDown'){e.preventDefault();idx=(idx+1)%items.length;this.setActiveSuggest(input,box,items,idx);}else if(e.key==='ArrowUp'){e.preventDefault();idx=(idx-1+items.length)%items.length;this.setActiveSuggest(input,box,items,idx);}else if(e.key==='Enter'&&idx>=0){e.preventDefault();this.pickSuggest(input,box,items[idx].dataset.value);}else if(e.key==='Tab'){this.hideSuggests();}},
 setActiveSuggest(input,box,items,idx){items.forEach(it=>it.classList.remove('active'));const item=items[idx];if(!item)return;item.classList.add('active');box.dataset.activeIndex=String(idx);input.setAttribute('aria-activedescendant',item.id);item.scrollIntoView({block:'nearest'});},
 showInputSuggest(id){if(id==='disease')this.showSuggest(document.getElementById('disease'),document.getElementById('diseaseSuggest'),this.getDiseaseOptions(),'疾病');if(id==='onsetPlace')this.showSuggest(document.getElementById('onsetPlace'),document.getElementById('placeSuggest'),this.getPlaceOptions(),'地点');},
 bindSuggestItem(it,input,box){const start=e=>{const p=this.getPoint(e);this.suggestTouch={x:p.x,y:p.y,moved:false,value:it.dataset.value};};const move=e=>{if(!this.suggestTouch)return;const p=this.getPoint(e);if(Math.abs(p.x-this.suggestTouch.x)>8||Math.abs(p.y-this.suggestTouch.y)>8)this.suggestTouch.moved=true;};const end=e=>{if(!this.suggestTouch)return;const touch=this.suggestTouch;this.suggestTouch=null;if(touch.moved)return;e.preventDefault();e.stopPropagation();this.pickSuggest(input,box,touch.value);};it.addEventListener('touchstart',start,{passive:true});it.addEventListener('touchmove',move,{passive:true});it.addEventListener('touchend',end,{passive:false});it.addEventListener('pointerdown',start);it.addEventListener('pointermove',move);it.addEventListener('pointerup',end);it.addEventListener('click',e=>e.preventDefault());},
 getPoint(e){const t=e.changedTouches&&e.changedTouches[0]||e.touches&&e.touches[0]||e;return{x:t.clientX||0,y:t.clientY||0};},
 pickSuggest(input,box,value){input.value=value;this.suppressSuggestUntil=Date.now()+300;this.hideSuggests();input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));this.updatePlaceRequired();if(document.activeElement===input)input.blur();},
 hideSuggests(){document.querySelectorAll('.suggest-list').forEach(b=>{b.classList.remove('show');b.dataset.activeIndex='-1';});document.querySelectorAll('[aria-expanded="true"]').forEach(el=>el.setAttribute('aria-expanded','false'));},
 getDiseaseOptions(){return this.unique(DEFAULT_DISEASES.concat(this.config.customDiseases||[]));},
 getPlaceOptions(){return this.unique(DEFAULT_PLACES.concat(this.config.customPlaces||[]));},
 isCustomOption(label,value){return label==='疾病'?(this.config.customDiseases||[]).includes(value):(this.config.customPlaces||[]).includes(value);},
 highlightText(value,kw){const text=this.escapeHtml(value);if(!kw)return text;const safeKw=this.escapeHtml(kw);return text.replace(safeKw,`<mark>${safeKw}</mark>`);},
 addCustom(type,value){const t=(value||'').trim();if(!t)return;if(type==='disease'&&!this.getDiseaseOptions().includes(t))this.config.customDiseases.push(t);if(type==='place'&&!this.getPlaceOptions().includes(t))this.config.customPlaces.push(t);this.config.customDiseases=this.unique(this.config.customDiseases||[]);this.config.customPlaces=this.unique(this.config.customPlaces||[]);},
 unique(list){return list.map(v=>String(v).trim()).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);},
 escapeHtml(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));},
 isPlaceRequired(){const d=document.getElementById('disease').value.trim(),visit=document.getElementById('visit').value;return PLACE_REQUIRED_DISEASES.includes(d)||visit==='是';},
 updatePlaceRequired(){const required=this.isPlaceRequired(),mark=document.getElementById('placeRequired'),input=document.getElementById('onsetPlace');mark.style.display=required?'inline':'none';input.placeholder=required?'请选择或输入发病地点（必填）':'请选择或输入发病地点（选填）';},
 showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000);},
 addRecord(){const park=document.getElementById('park').value,personType=document.getElementById('personType').value,disease=document.getElementById('disease').value.trim(),onsetPlace=document.getElementById('onsetPlace').value.trim(),doctor=document.getElementById('doctor').value.trim(),visit=document.getElementById('visit').value;if(!disease){this.showToast('请输入疾病名称！');return this.focusInput(document.getElementById('disease'));}if(this.isPlaceRequired()&&!onsetPlace){this.showToast('请填写发病地点！');return this.focusInput(document.getElementById('onsetPlace'));}if(!doctor){this.showToast('请输入医生姓名！');return this.focusInput(document.getElementById('doctor'));}this.records.push({park,personType,disease,onsetPlace,doctor,visit,timestamp:Date.now()});this.addCustom('disease',disease);this.addCustom('place',onsetPlace);this.config.lastPark=park;this.config.lastDoctor=doctor;this.saveConfig();document.getElementById('disease').value='';document.getElementById('onsetPlace').value='';document.getElementById('visit').value='否';this.updatePlaceRequired();this.hideSuggests();if(document.activeElement)document.activeElement.blur();this.updateRecordList();this.showToast('记录添加成功！');},
 updateRecordList(){const el=document.getElementById('recordList');if(this.records.length===0){el.innerHTML='<div class="empty-state">暂无记录</div>';return;}el.innerHTML=this.records.map(r=>`<div class="record-item"><strong>${r.park} - ${r.personType}</strong><br>${r.disease}${r.onsetPlace?` | 发病地点：${r.onsetPlace}`:''} | 医生：${r.doctor}${r.visit==='是'?' | 出诊：是':''}</div>`).join('');},
 clearRecords(){if(this.records.length===0)return this.showToast('没有记录可清除');if(!confirm('确定要清除所有记录吗？'))return;this.records=[];this.tableRows=[];this.updateRecordList();document.getElementById('reportPreview').innerHTML='';document.getElementById('reportActions').style.display='none';document.getElementById('tablePreview').innerHTML='';document.getElementById('tableActions').style.display='none';this.showToast('记录已清除');},
 formatDate(){const d=new Date();return `${d.getFullYear()}年${String(d.getMonth()+1).padStart(2,'0')}月${String(d.getDate()).padStart(2,'0')}日`;},
 groupByPark(){return this.records.reduce((res,r)=>{if(!res[r.park])res[r.park]={游客:{},员工:{},出诊:[],records:[]};res[r.park].records.push(r);res[r.park][r.personType][r.disease]=(res[r.park][r.personType][r.disease]||0)+1;if(this.isVisitRecord(r))res[r.park].出诊.push(this.getRecordPlace(r));return res;},{});},
 isVisitRecord(r){return r.visit==='是'||r.visit===true||!!r.location;},
 getRecordPlace(r){return (r.onsetPlace||r.location||'').trim();},
 generateReport(){if(this.records.length===0)return this.showToast('请先添加记录！');const date=this.formatDate(),byPark=this.groupByPark();let report='';Object.entries(byPark).forEach(([park,data])=>{const tc=this.sum(data.游客),sc=this.sum(data.员工),total=tc+sc;report+=`${date}欢乐谷医务室（${park}）当日接诊共${total}人。\n`;if(tc>0)report+=`游客${tc}人：${this.formatSummary(data.游客)}。\n`;if(sc>0)report+=`员工${sc}人：${this.formatSummary(data.员工)}。\n`;if(data.出诊.length>0)report+=`当日出诊${data.出诊.length}次：${this.formatVisitSummary(data.出诊)}。\n`;report+='\n';});document.getElementById('reportPreview').innerHTML=`<div class="report-preview">${report}</div>`;document.getElementById('reportActions').style.display='grid';this.showToast('日报生成成功！');},
 generateTable(){if(this.records.length===0)return this.showToast('请先添加记录！');this.tableRows=[];const date=this.formatDate(),byPark=this.groupByPark();let html='<div class="table-container">';Object.entries(byPark).forEach(([park,data])=>{const parkRows=[this.buildPersonRow(data.records,'游客',date),this.buildPersonRow(data.records,'员工',date)].filter(r=>r.count>0).map(r=>r.values);this.tableRows.push(...parkRows);html+=`<h3>${park} - ${date}</h3>${this.renderTable(parkRows)}`;});document.getElementById('tablePreview').innerHTML=html+'</div>';document.getElementById('tableActions').style.display='grid';this.showToast('表格生成成功！');},
 buildPersonRow(records,type,date){const row=Array(TABLE_HEADERS.length).fill(''),docs=[],other={},scratchPlaces=[],fracturePlaces=[],visitPlaces=[];let count=0;row[0]=date;records.filter(r=>r.personType===type&&r.disease).forEach(r=>{if(TABLE_DISEASE_COLUMNS.includes(r.disease)){const i=TABLE_HEADERS.indexOf(r.disease);row[i]=String((Number(row[i])||0)+1);}else other[r.disease]=(other[r.disease]||0)+1;if(r.disease==='擦伤'&&this.getRecordPlace(r)&&!scratchPlaces.includes(this.getRecordPlace(r)))scratchPlaces.push(this.getRecordPlace(r));if(r.disease==='骨折'&&this.getRecordPlace(r)&&!fracturePlaces.includes(this.getRecordPlace(r)))fracturePlaces.push(this.getRecordPlace(r));if(this.isVisitRecord(r)&&this.getRecordPlace(r))visitPlaces.push(this.getRecordPlace(r));count++;if(r.doctor&&!docs.includes(r.doctor))docs.push(r.doctor);});if(scratchPlaces.length)row[3]=scratchPlaces.join('、');if(fracturePlaces.length)row[13]=fracturePlaces.join('、');if(Object.keys(other).length>0)row[TABLE_HEADERS.indexOf('其他')]=`${this.sum(other)}人：${this.formatSummary(other)}`;row[TABLE_HEADERS.indexOf('合计')]=count?String(count):'';row[TABLE_HEADERS.indexOf('接诊医生')]=docs.join('、');if(visitPlaces.length)row[TABLE_HEADERS.indexOf('备注')]=`出诊${visitPlaces.length}次：${this.formatVisitSummary(visitPlaces)}`;return{count,values:row};},
 buildVisitRow(place,date){const row=Array(TABLE_HEADERS.length).fill('');row[0]=date;row[3]=place;row[13]=place;row[TABLE_HEADERS.indexOf('备注')]=place?`出诊：${place}1次`:'出诊1次';return row;},
 renderTable(rows){if(rows.length===0)return'<div class="empty-state">暂无表格数据</div>';const head=TABLE_HEADERS.map(h=>`<th>${h}</th>`).join(''),body=rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('');return`<table class="data-table"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;},
 copyFullTable(){if(this.tableRows.length===0)return this.showToast('请先生成表格！');this.copyToClipboard(this.tableRows.map(r=>r.slice(1).join('\t')).join('\n'),`表格数据（共${this.tableRows.length}行，不含表头和日期）`);},
 copyPersonTable(type){if(this.records.length===0)return this.showToast('没有数据可复制！');const rows=[];Object.values(this.groupByPark()).forEach(data=>{const row=this.buildPersonRow(data.records,type,this.formatDate());if(row.count>0)rows.push(row.values.slice(1).join('\t'));});if(rows.length===0)return this.showToast(`没有${type}数据！`);this.copyToClipboard(rows.join('\n'),`${type}表格数据`);},
 copyTouristTable(){this.copyPersonTable('游客');},copyStaffTable(){this.copyPersonTable('员工');},
 copyReport(){const el=document.querySelector('.report-preview');if(!el)return this.showToast('请先生成日报！');this.copyToClipboard(el.textContent,'日报');},
 fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');this.showToast('已复制到剪贴板！');}catch(e){this.showToast('复制失败，请手动复制');}document.body.removeChild(ta);},
 copyToClipboard(text,name){if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>this.showToast(`${name}已复制到剪贴板！`)).catch(()=>this.fallbackCopy(text));else this.fallbackCopy(text);},
 shareReport(){const el=document.querySelector('.report-preview');if(!el)return this.showToast('请先生成日报！');if(navigator.share)navigator.share({title:'欢乐谷医务室日报',text:el.textContent}).then(()=>this.showToast('分享成功！')).catch(()=>this.copyReport());else this.copyReport();},
 sum(data){return Object.values(data).reduce((s,v)=>s+v,0);},formatSummary(data){return Object.entries(data).map(([d,c])=>`${d}${c}人`).join('，');},formatVisitSummary(list){const map={};list.forEach(p=>{map[p]=(map[p]||0)+1;});return Object.entries(map).map(([p,c])=>`${p}${c}次`).join('，');}
};
document.addEventListener('DOMContentLoaded',()=>app.init());
